version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      # - ./config/:/etc/grafana/
      - ./data/:/var/lib/grafana/
