version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Origin: ['http://127.0.0.1:8080']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
  # tls:
  #   certificate: /fullchain1.pem
  #   key: /privkey1.pem
# auth:
#   htpasswd:
#     realm: basic-realm
#     path: /.htpasswd
